server {
    listen 4173;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /interactivetool/ep/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    # Handle regular assets
    # TODO: might not be needed, remove 
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
    }
}
