server {
    listen 4173;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /interactivetool/ep/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Inject NODE_ENV into the response header
    add_header X-Node-Env "$NODE_ENV";
    try_files $uri $uri/ /index.html;
    }
}

